### ISSUE TITLE
Cannot Import More Than One json Model

### ISSUE THREAD

**Issue by pasetti** [pnp-software/fwprofile-editor-pub#9]
I do not seem to be able to import more than one model into the editor. Here is what I do:

(1) I go to `www.pnp-software.com/fwprofile/editor` and log in the editor. 
(2) I go to "Actions", select "Import json" and successfully import a new model
(3) After the newly imported model has been saved, I go to "presets" and select "New Procedure"
(4) I now have a clean canvas and I go again to "Actions" and select "Import json" but this time the import operation fails (I do not get any error messages but the model which I have selected for import is not imported and the canvas remains blank)

In order to make the import function work again, I must close the browser tab with the editor and then open a new one and re-start the editor in the new tab. After this is done, I can import one model in the browser (but only one -- afterwards, I get the same behaviour as described above).

**Comment by Tomas-M** [comment]
I noticed it happens when user tries to import the same file name again. It remembers what was the previous filename and thus it thinks the file is already selected and does not trigger the "change" event when the same file is loaded.

It has been addressed here 26901d27bc232378b10ecbf20a19f5cbb5ebed25
I've also made the same change to fcp-editor sources.
Let me know please if this does not fix your issue, otherwise I consider this as fixed.

**Comment by Tomas-M** [comment]
Hm this is strange.

First of all, let me clarify, the import is made on client's side only. That means you will not find any error messages related to this problem in server's error_log file, since everything happens in the browser only (you should be able to reproduce the same problem simply without saving the diagram to server)

To make sure you are using fixed sources, please try to force browser to hard-reload (Ctrl+F5 on the editor's window).
Then you can try simply
1) import JSON file
2) right away attempt to import another JSON file
(no saving necessary)

In your point number (6), you say the import action fails. Does this mean that after selecting the file, the green IMPORT button does not appear at all? Or does it mean that it appears, but clicking it does nothing?

Thank you

**Comment by pasetti** [comment]
I have tried the experiment you have suggested on Firefox and then on Chrome and I think that the error only occurs on Firefox. Here is what I have done:

(1) I go to Firefox and log in to a localhost version of the editor (I am using the very latest version which includes the update which you did this morning).
(2) I do  <ctrl-F5> 
(3) I go to "Actions-->Import" and I get a file picker where I choose a json file to be imported. The editor shows the following screenshot:

![Screenshot1](https://user-images.githubusercontent.com/15838404/137586989-1cd5adf0-22e3-4577-809f-f1561777c928.png)

(4) When I press "import", I get an "import successful" message and I can see the newly loaded model on the canvas. This is the behaviour I would expect.
(5) I go again to "Actions-->Import" and I get again a file picker where I select a different json file to be imported. This time, the editor does not show any import message and what I see after selecting a file is simply:

![Screenshot2](https://user-images.githubusercontent.com/15838404/137587026-a781f005-e886-4a73-a59d-49821b3b532e.png)

(6) When i go back to the editor canvas, I have again the model I had loaded at point (4). This means that it is impossible to import a second model.
(7) I press "save" and I get a "save successful" message 

From this moment onward, the load-save mechanism no longer works properly on the client-side: if I load a model from the repository and then change it and save it, the changes appear to be lost in the sense that if I re-load the same model at a later time **and within the same session**, the changes are not visible. If, however, I close the browser tab and then open it again, the changes re-appear. My impression is that the attempt to import a second json model has somehow confused the client side of the editor which becomes unable to keep track of changes made to models (but the changes are correctly recorded on server-side).

To add to the confusion, I should add that, if I repeat exactly the same test on **Chrome**, then I get a nominal behaviour. So the problem, appears to be browser-dependent. I should add something else. I do not often use the import function of the editor but I am sure that I did use it a few times many years ago and I do not recall noticing any problem. Hence, the problem might be due to some recent update of Firefox (I am using Firefox 93.0 on an Ubuntu 18.04 platform).

**Comment by Tomas-M** [comment]
Seems like the way how the file input element is cloned makes some troubles in firefox.
Since the value is reset just fine (commited earlier), I just removed the element cloning here
ebba87426ed601c31d021468483126f6f33fe09d

Please test. Thank you.

**Comment by pasetti** [comment]
I have verified the latest update (the removal of the element cloning in commit https://github.com/pnp-software/fwprofile-editor-pub/commit/ebba87426ed601c31d021468483126f6f33fe09d. This change does indeed solve the import problem in Firefox (i.e. with this change, it is possible to import multiple models into the editor running under Firefox) and, as far as I can tell, it also solves the problem described in #8. 

I think I am ready to close the ticket but I have one last question for Tomas: I suppose I should also duplicate this change in FCP Editor. Right? If this is confirmed, I will update both editor instances running on our server.

And then I will close the ticket with many thanks for @Tomas-M  for his prompt response!

**Comment by Tomas-M** [comment]
Actually I've already pushed the changes to FCP-editor github. so just please verify it works there.

**Comment by pasetti** [comment]
I just checked the FCP Editor and it works as expected. I proceed to close the ticket.
